---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    workload.openshift.io/allowed: management
  name: openshift-gitops-operator
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator 
spec:
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
