---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: infra.5g-deployment.lab:8443/hub-demo/redhat/redhat-operator-index:v4.18
  sourceType: grpc