apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: mno-wp-sched-master
spec:
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 70
        size: 1G
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ''
  nodeSelector:
    node-role.kubernetes.io/master: ''
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
