apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: mno-wp-sched-worker
  annotations:
    kubeletconfig.experimental: |
      {"systemReserved": {"memory": "8Gi"}, "topologyManagerScope": "pod"}
spec:
  cpu:
    isolated: 2-19,22-39       # Use 36 cores for workload
    reserved: 0-1,20-21       # Reserve 4 cores for system/kubelet
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - count: 32
        size: "1G"
        node: 0
  kernelPageSize: 4k
  net:
    userLevelNetworking: true
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
  workloadHints:
    highPowerConsumption: false
    realTime: false
    perPodPowerManagement: true
  globallyDisableIrqLoadBalancing: false
  additionalKernelArgs:
    - "nohz_full=2-19,22-39"