---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: multiclusterengine
  labels:
    app.kubernetes.io/instance: hub-operators-config
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
    multiclusterhubs.operator.open-cluster-management.io/managed-by: "true"
spec:
  availabilityConfig: Basic
  targetNamespace: multicluster-engine
  overrides:
    components:
    - name: image-based-install-operator
      enabled: true
      configOverrides: {}
    - name: hypershift
      enabled: false
      configOverrides: {}
    - name: hypershift-local-hosting
      enabled: false
      configOverrides: {}
