---
apiVersion: v1
kind: Secret
Metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: '{{ fromConfigMap "open-cluster-management-observability" "thanos-s3" "BUCKET_NAME" | toLiteral }}'
      endpoint: s3.openshift-storage.svc
      insecure: false
      access_key: '{{ fromSecret "open-cluster-management-observability" "thanos-s3" "AWS_ACCESS_KEY_ID" | base64dec | toLiteral }}'
      secret_key: '{{ fromSecret "open-cluster-management-observability" "thanos-s3" "AWS_SECRET_ACCESS_KEY" | base64dec | toLiteral }}'
      http_config:
        tls_config:
        ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
---
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: observability
  namespace: open-cluster-management-observability
spec:
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: ocs-storagecluster-ceph-rbd
    storeStorageSize: 10Gi
