---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: local-block
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - master0.b11oe21mno.dyn.onebts.example.com
        - master1.b11oe21mno.dyn.onebts.example.com
        - master2.b11oe21mno.dyn.onebts.example.com
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-path/pci-0000:00:11.5-ata-3
    storageClassName: localblock
    volumeMode: Block

