---
apiVersion: v1
kind: Namespace
metadata:
  name: quay-operator
  annotations:
    openshift.io/node-selector: ''
    workload.openshift.io/allowed: management
    argocd.argoproj.io/sync-wave: "3"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator
  namespace: quay-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  targetNamespaces:
    - quay-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-operator
  annotations:
<<<<<<< HEAD
    argocd.argoproj.io/sync-wave: "3"
=======
    ran.openshift.io/ztp-deploy-wave: "2"
    argocd.argoproj.io/healthcheck: None
>>>>>>> d807d61 (update oadp and quay)
spec:
  name: quay-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic