---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    workload.openshift.io/allowed: management
  name: openshift-kmm-hub
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: openshift-kmm-hub
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    olm.providedAPIs: ManagedClusterModule.v1beta1.hub.kmm.sigs.x-k8s.io,ModuleBuildSignConfig.v1beta1.kmm.sigs.x-k8s.io,ModuleImagesConfig.v1beta1.kmm.sigs.x-k8s.io
  name: openshift-kmm-hub-group
  namespace: openshift-kmm-hub
spec:
  targetNamespaces:
  - openshift-kmm-hub
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    operators.coreos.com/kernel-module-management-hub.openshift-kmm-hub: ""
  name: kernel-module-management-hub
  namespace: openshift-kmm-hub
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kernel-module-management-hub
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
