---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
  annotations:
    openshift.io/node-selector: ''
    workload.openshift.io/allowed: management
    ran.openshift.io/ztp-deploy-wave: "2"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-oadp-operator
  namespace: openshift-adp
  annotations:
    operatorframework.io/bundle-unpack-min-retry-interval: 5m
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  targetNamespaces:
    - openshift-adp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-adp
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  name: redhat-oadp-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic