apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certified-operator-index
  namespace: openshift-marketplace
spec:
  image: registry.redhat.io/redhat/certified-operator-index:v4.18
  sourceType: grpc