---
apiVersion: v1
kind: Secret
metadata:
  name: seedgen
  namespace: openshift-lifecycle-agent
type: Opaque
data:
  seedAuth: "ewogICJhdXRocyI6IHsKICAgICJpbmZyYS41Zy1kZXBsb3ltZW50LmxhYjo4NDQzIjogewogICAgICAiYXV0aCI6ICJjR2s2Y21GemNHSmxjbko1IiwKICAgICAgImVtYWlsIjogImpoZW5kcml4QGthcm1hbGFicy5jb3JwIgogICAgfQogIH0KfQoK"
---
apiVersion: lca.openshift.io/v1
kind: SeedGenerator
metadata:
  name: seedimage
spec:
  seedImage: infra.5g-deployment.lab:8443/sno1/seedimage-ibu-upgrade:4.18.27-x86_64